import type { Metadata } from "next";
import "./globals.css";

import { Public_Sans } from "next/font/google";
import { Kings } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import PageTransition from "@/components/pageTransition"; // Import the new client component
import { ThemeProvider } from "@/components/theme-providers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-public-sans", // Optional: CSS variable for custom usage
});

const kings = Kings({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kings", // Optional: CSS variable for custom usage
});

export const metadata: Metadata = {
  title: "Axiom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${kings.variable} antialiased overflow-x-hidden bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <SidebarTrigger className="fixed top-3 left-3 dark:bg-neutral-900 dark:text-white w-11 h-11" />
            <PageTransition>{children}</PageTransition>
            <Toaster />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
